name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t food-delivery-frontend .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Push to Docker Hub
      run: |
        docker tag food-delivery-frontend ${{ secrets.DOCKER_HUB_USERNAME }}/food-delivery-frontend:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/food-delivery-frontend:latest

